const mensItems = [
  {
    id: 1,
    title: "Denim Jacket",
    image: "images/men/men 1.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 2,
    title: "Denim Jacket",
    image: "images/men/men 2.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 3,
    title: "Denim Jacket",
    image: "images/men/men 3.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 4,
    title: "Denim Jacket",
    image: "images/men/men 4.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 5,
    title: "Denim Jacket",
    image: "images/men/men 5.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 6,
    title: "Denim Jacket",
    image: "images/men/men 6.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 7,
    title: "Denim Jacket",
    image: "images/men/men 7.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 8,
    title: "Denim Jacket",
    image: "images/men/men 8.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 9,
    title: "Denim Jacket",
    image: "images/men/men 9.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 10,
    title: "Denim Jacket",
    image: "images/men/men 10.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 11,
    title: "Denim Jacket",
    image: "images/men/men 11.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 12,
    title: "Denim Jacket",
    image: "images/men/men 2.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 13,
    title: "Denim Jacket",
    image: "images/men/men 3.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 14,
    title: "Denim Jacket",
    image: "images/men/men 4.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 15,
    title: "Denim Jacket",
    image: "images/men/men 5.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
];

export default mensItems;