const mensItems = [
  {
    id: 01,
    title: "Denim Jacket",
    image: "images/men/men 1.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 02,
    title: "Denim Jacket",
    image: "images/men/men 2.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 03,
    title: "Denim Jacket",
    image: "images/men/men 3.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 04,
    title: "Denim Jacket",
    image: "images/men/men 4.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 05,
    title: "Denim Jacket",
    image: "images/men/men 5.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 06,
    title: "Denim Jacket",
    image: "images/men/men 6.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 07,
    title: "Denim Jacket",
    image: "images/men/men 7.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 08,
    title: "Denim Jacket",
    image: "images/men/men 8.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 09,
    title: "Denim Jacket",
    image: "images/men/men 9.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 010,
    title: "Denim Jacket",
    image: "images/men/men 10.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 011,
    title: "Denim Jacket",
    image: "images/men/men 11.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 012,
    title: "Denim Jacket",
    image: "images/men/men 12.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 013,
    title: "Denim Jacket",
    image: "images/men/men 13.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 014,
    title: "Denim Jacket",
    image: "images/men/men 14.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 015,
    title: "Denim Jacket",
    image: "images/men/men 15.jpeg",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
];

export default mensItems;