const mensItems = [
  {
    id: 1,
    title: "Denim Jacket",
    image: "images/men/men 1.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 2,
    title: "Denim Jacket",
    image: "images/men/men 2.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 3,
    title: "Denim Jacket",
    image: "images/men/men 3.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 4,
    title: "Denim Jacket",
    image: "images/men/men 4.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 5,
    title: "Denim Jacket",
    image: "images/men/men 5.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 6,
    title: "Denim Jacket",
    image: "images/men/men 6.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 7,
    title: "Denim Jacket",
    image: "images/men/men 7.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 8,
    title: "Denim Jacket",
    image: "images/men/men 8.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 9,
    title: "Denim Jacket",
    image: "images/men/men 9.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 10,
    title: "Denim Jacket",
    image: "images/men/men 10.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 11,
    title: "Denim Jacket",
    image: "images/men/men 11.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 12,
    title: "Denim Jacket",
    image: "images/men/men 1.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 13,
    title: "Denim Jacket",
    image: "images/men/men 3.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 14,
    title: "Denim Jacket",
    image: "images/men/men 4.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
  {
    id: 15,
    title: "Denim Jacket",
    image: "images/men/men 5.webp",
    description: "This is item 1",
    Price: 590.99,
    type: "mens collection",
  },
];

export default mensItems;